### PR TITLE
Moved classes, modules to TOML namespace to removed potential conflict. Fix #68

### LINKED ISSUE #68: Put all modules under TOML namespace
Now `toml-rb` creates very many global constants:

* Document
* Helper
* InlineTable
* InlineTableArray
* Keygroup
* Keyvalue
* Primitive
* and many other which start with Toml

Several of these constants are very dangerous (like Document, Helper, Primitive) as they might overlap with application specific classes or modules.

All these constants should be moved under just one TOML namespace (as it seems that Citrus allows to use e.g. `grammar TOML::Document`).

### PR DESCRIPTION
**Pull request by timcolonel**
Moved every classes, modules that where in the global namespace inside TOML. 
Renamed as well classes named TomlSomeCass to TOML::SomeClass
Needed to rename the Array grammar to Arrays as having TOML::Array would cause error.
I also added Parser at the end of the module used in citrus(TableArray => TOML::TableArrayParser)

### CODE REVIEW

**Comment by emancu** [comment]
Thanks for your PR.

I'll review it tonight or tomorrow.

**Comment by emancu** [comment]
It seems to be correct! :+1: 

Could you please fix the comments made by @houndci ?

**Comment by emancu** [comment]
@timcolonel you can run `rubocop` on the project directory to check if there is any style issue.

**Comment by timcolonel** [comment]
Ok thanks will fix that now.

**Comment by timcolonel** [comment]
I fixed the hound violations however rubocop sill show about 10 errors about Assignment Branch Condition size being to big.

**Comment by emancu** [comment]
Don't worry about those errors.

**Pull request merged**
