### PR TITLE
Please support dotted_keys

### PR DESCRIPTION
**Pull request by yassun4dev**
Release [toml v0.5.0](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md).
First, please support "dotted key".

Change points
- [x] Add dotted keys.
- [ ] Add hex, octal, and binary integer formats.
- [ ] Add special float values (inf, nan)
- [ ] Rename Datetime to Offset Date-Time.
- [ ] Add Local Date-Time.
- [ ] Add Local Date.
- [ ] Add Local Time.
- [ ] Allow space (instead of T) to separate date and time in Date-Time.

### CODE REVIEW

**Comment by yassun4dev** [comment]
Thanks.
There is no ruby ​​library corresponding to v0.5.0 yet, 
so I hope you'll support with it.

**Comment by emancu** [comment]
I didn't forget about this, I'm just super busy but I will support 0.5 asap. Probably before March.

**Comment by yassun4dev** [comment]
Thanks.
I’m looking forward to being updated.

**Comment by emancu** [comment]
I didn't forget about this PR. I am working on the support for Toml 0.5 which is taking longer than expected.

I am considering to just merge this and then refactor. Will see what is better.

Hope to have updates soon!

**Comment by yassun4dev** [comment]
Sorry, I didn't notice your reply :(
For toml v0.5.0 support, I make a new pull request.
Please close this request?

**Pull request closed without merging**
