### PR TITLE
Add trailing whitespace for keyvalue and line_break rules

### PR DESCRIPTION
**Pull request by rodzhers**
Fixes error when there is a trailing whitespace at the end of the document.

### CODE REVIEW

**Comment by rodzhers** [comment]
I cannot reproduce lint errors on my local machine, as running `bundle exec rake standard` produces no errors. 
Also, the linter issues seem to be in files outside the scope of this PR in files with single-quote strings.

**Comment by emancu** [comment]
@rodzhers don't worry, I will fix the lint now; you should be able to rebase

**Comment by emancu** [comment]
Done https://github.com/emancu/toml-rb/pull/129

**Comment by emancu** [comment]
Your changes were released in v2.0.2

**Pull request merged**
